version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: npm install
          command: npm i
      - run:
          name: gulp build
          command: npm run build